// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node.proto

#include "node.pb.h"
#include "node.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* SystemNodeConfig_method_names[] = {
  "/SystemNodeConfig/SendSystemNodeConfig",
};

std::unique_ptr< SystemNodeConfig::Stub> SystemNodeConfig::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SystemNodeConfig::Stub> stub(new SystemNodeConfig::Stub(channel));
  return stub;
}

SystemNodeConfig::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendSystemNodeConfig_(SystemNodeConfig_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SystemNodeConfig::Stub::SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::NodeConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendSystemNodeConfig_, context, request, response);
}

void SystemNodeConfig::Stub::experimental_async::SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS* request, ::NodeConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendSystemNodeConfig_, context, request, response, std::move(f));
}

void SystemNodeConfig::Stub::experimental_async::SendSystemNodeConfig(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NodeConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendSystemNodeConfig_, context, request, response, std::move(f));
}

void SystemNodeConfig::Stub::experimental_async::SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS* request, ::NodeConfigResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendSystemNodeConfig_, context, request, response, reactor);
}

void SystemNodeConfig::Stub::experimental_async::SendSystemNodeConfig(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NodeConfigResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendSystemNodeConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NodeConfigResponse>* SystemNodeConfig::Stub::AsyncSendSystemNodeConfigRaw(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::NodeConfigResponse>::Create(channel_.get(), cq, rpcmethod_SendSystemNodeConfig_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::NodeConfigResponse>* SystemNodeConfig::Stub::PrepareAsyncSendSystemNodeConfigRaw(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::NodeConfigResponse>::Create(channel_.get(), cq, rpcmethod_SendSystemNodeConfig_, context, request, false);
}

SystemNodeConfig::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SystemNodeConfig_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SystemNodeConfig::Service, ::ConfigNodeS, ::NodeConfigResponse>(
          std::mem_fn(&SystemNodeConfig::Service::SendSystemNodeConfig), this)));
}

SystemNodeConfig::Service::~Service() {
}

::grpc::Status SystemNodeConfig::Service::SendSystemNodeConfig(::grpc::ServerContext* context, const ::ConfigNodeS* request, ::NodeConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


