// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node.proto
#ifndef GRPC_node_2eproto__INCLUDED
#define GRPC_node_2eproto__INCLUDED

#include "node.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

class SystemNodeConfig final {
 public:
  static constexpr char const* service_full_name() {
    return "SystemNodeConfig";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::NodeConfigResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NodeConfigResponse>> AsyncSendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NodeConfigResponse>>(AsyncSendSystemNodeConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NodeConfigResponse>> PrepareAsyncSendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NodeConfigResponse>>(PrepareAsyncSendSystemNodeConfigRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS* request, ::NodeConfigResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendSystemNodeConfig(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NodeConfigResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS* request, ::NodeConfigResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void SendSystemNodeConfig(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NodeConfigResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NodeConfigResponse>* AsyncSendSystemNodeConfigRaw(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NodeConfigResponse>* PrepareAsyncSendSystemNodeConfigRaw(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::NodeConfigResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NodeConfigResponse>> AsyncSendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NodeConfigResponse>>(AsyncSendSystemNodeConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NodeConfigResponse>> PrepareAsyncSendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NodeConfigResponse>>(PrepareAsyncSendSystemNodeConfigRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS* request, ::NodeConfigResponse* response, std::function<void(::grpc::Status)>) override;
      void SendSystemNodeConfig(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NodeConfigResponse* response, std::function<void(::grpc::Status)>) override;
      void SendSystemNodeConfig(::grpc::ClientContext* context, const ::ConfigNodeS* request, ::NodeConfigResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void SendSystemNodeConfig(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NodeConfigResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NodeConfigResponse>* AsyncSendSystemNodeConfigRaw(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NodeConfigResponse>* PrepareAsyncSendSystemNodeConfigRaw(::grpc::ClientContext* context, const ::ConfigNodeS& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendSystemNodeConfig_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendSystemNodeConfig(::grpc::ServerContext* context, const ::ConfigNodeS* request, ::NodeConfigResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendSystemNodeConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendSystemNodeConfig() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendSystemNodeConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendSystemNodeConfig(::grpc::ServerContext* /*context*/, const ::ConfigNodeS* /*request*/, ::NodeConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendSystemNodeConfig(::grpc::ServerContext* context, ::ConfigNodeS* request, ::grpc::ServerAsyncResponseWriter< ::NodeConfigResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendSystemNodeConfig<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SendSystemNodeConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SendSystemNodeConfig() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::ConfigNodeS, ::NodeConfigResponse>(
          [this](::grpc::ServerContext* context,
                 const ::ConfigNodeS* request,
                 ::NodeConfigResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->SendSystemNodeConfig(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_SendSystemNodeConfig(
        ::grpc::experimental::MessageAllocator< ::ConfigNodeS, ::NodeConfigResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::ConfigNodeS, ::NodeConfigResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SendSystemNodeConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendSystemNodeConfig(::grpc::ServerContext* /*context*/, const ::ConfigNodeS* /*request*/, ::NodeConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void SendSystemNodeConfig(::grpc::ServerContext* /*context*/, const ::ConfigNodeS* /*request*/, ::NodeConfigResponse* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_SendSystemNodeConfig<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendSystemNodeConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendSystemNodeConfig() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendSystemNodeConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendSystemNodeConfig(::grpc::ServerContext* /*context*/, const ::ConfigNodeS* /*request*/, ::NodeConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendSystemNodeConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendSystemNodeConfig() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendSystemNodeConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendSystemNodeConfig(::grpc::ServerContext* /*context*/, const ::ConfigNodeS* /*request*/, ::NodeConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendSystemNodeConfig(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SendSystemNodeConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SendSystemNodeConfig() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->SendSystemNodeConfig(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_SendSystemNodeConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendSystemNodeConfig(::grpc::ServerContext* /*context*/, const ::ConfigNodeS* /*request*/, ::NodeConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void SendSystemNodeConfig(::grpc::ServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendSystemNodeConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendSystemNodeConfig() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::ConfigNodeS, ::NodeConfigResponse>(std::bind(&WithStreamedUnaryMethod_SendSystemNodeConfig<BaseClass>::StreamedSendSystemNodeConfig, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_SendSystemNodeConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendSystemNodeConfig(::grpc::ServerContext* /*context*/, const ::ConfigNodeS* /*request*/, ::NodeConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendSystemNodeConfig(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ConfigNodeS,::NodeConfigResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendSystemNodeConfig<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendSystemNodeConfig<Service > StreamedService;
};


#endif  // GRPC_node_2eproto__INCLUDED
